In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('weatherHistory.csv')
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [3]:
df = df.drop_duplicates()
print("Kích thước dữ liệu sau khi xóa dòng trùng:", df.shape)

Kích thước dữ liệu sau khi xóa dòng trùng: (96429, 12)

In [4]:
df['Formatted Date'] = pd.to_datetime(df['Formatted Date'], utc=True, errors='coerce')
df['Formatted Date'].head()

0   2006-03-31 22:00:00+00:00
1   2006-03-31 23:00:00+00:00
2   2006-04-01 00:00:00+00:00
3   2006-04-01 01:00:00+00:00
4   2006-04-01 02:00:00+00:00
Name: Formatted Date, dtype: datetime64[ns, UTC]

In [5]:
df['Year'] = df['Formatted Date'].dt.year
df['Month'] = df['Formatted Date'].dt.month
df['Day'] = df['Formatted Date'].dt.day
df['Hour'] = df['Formatted Date'].dt.hour

df[['Formatted Date', 'Year', 'Month', 'Day', 'Hour']].head()

             Formatted Date  Year  Month  Day  Hour
0 2006-03-31 22:00:00+00:00  2006      3   31    22
1 2006-03-31 23:00:00+00:00  2006      3   31    23
2 2006-04-01 00:00:00+00:00  2006      4    1     0
3 2006-04-01 01:00:00+00:00  2006      4    1     1
4 2006-04-01 02:00:00+00:00  2006      4    1     2

In [6]:
print(df.isnull().sum())

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
Year                          0
Month                         0
Day                           0
Hour                          0
dtype: int64

In [7]:
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Đã xử lý thiếu cho cột dạng chuỗi")
print(df[cat_cols].isnull().sum())

Đã xử lý thiếu cho cột dạng chuỗi
Summary          0
Precip Type      0
Daily Summary    0
dtype: int64

In [8]:
num_cols = df.select_dtypes(include=np.number).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

print("Đã xử lý thiếu cho cột số")
print(df[num_cols].isnull().sum())

Đã xử lý thiếu cho cột số
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Year                        0
Month                       0
Day                         0
Hour                        0
dtype: int64

In [9]:
label_encoders = {}
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,Year,Month,Day,Hour
0,2006-03-31 22:00:00+00:00,19,0,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,197,2006,3,31,22
1,2006-03-31 23:00:00+00:00,19,0,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,197,2006,3,31,23
2,2006-04-01 00:00:00+00:00,17,0,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,197,2006,4,1,0
3,2006-04-01 01:00:00+00:00,19,0,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,197,2006,4,1,1
4,2006-04-01 02:00:00+00:00,17,0,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,197,2006,4,1,2

In [10]:
df.to_csv('weather_cleaned.csv', index=False)
print("Đã lưu file weather_cleaned.csv")

Đã lưu file weather_cleaned.csv